# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - test
  - stack-analysis

before_script:
  - rustup default stable
  - rustup target add thumbv7em-none-eabihf
  - rustup component add rustfmt

formatting:
  stage: test

  script:
  - rustc --version && cargo --version
  - cargo fmt -- --check

building:
  stage: test

  script:
  - rustc --version && cargo --version
  - cargo check --all --examples


stack-analysis:
  stage: stack-analysis

  before_script:
    - rustup default nightly
    - rustup target add thumbv7em-none-eabihf
    - rustup component add llvm-tools-preview
    - rustup default stable
    - rustup target add thumbv7em-none-eabihf
    - rustup component add llvm-tools-preview
    - cargo install cargo-binutils
    - cargo +stable install cargo-call-stack

  script:
  - ./etc/verify-stack-usage.sh
