# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

before_script:
  - rustup default stable
  - rustup target add thumbv7em-none-eabihf
  - rustup component add rustfmt

test:formatting:
  script:
  - rustc --version && cargo --version
  - cargo fmt -- --check

test:cargo-check:
  script:
  - rustc --version && cargo --version
  - cargo check --all --examples
